In [6]:
import tensorflow as tf

In [8]:
x=tf.constant([1])

In [9]:
x.shape

TensorShape([1])

In [10]:
print(x)

tf.Tensor([1], shape=(1,), dtype=int32)


In [24]:
y=tf.constant([2,7,5,3,3])

In [12]:
tf.add(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 8, 6, 4])>

In [15]:
tf.math.multiply(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 7, 5, 3])>

In [21]:
x1=tf.constant([[1,2,2,3,4,], [2,3,4,5,6]])

In [22]:
tf.multiply(x,x1)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 2, 3, 4],
       [2, 3, 4, 5, 6]])>

In [25]:
tf.multiply(x1,y)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 2, 14, 10,  9, 12],
       [ 4, 21, 20, 15, 18]])>

In [27]:
tf.random(2)

TypeError: 'module' object is not callable